# Generated by Django 3.2.18 on 2023-03-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationpeople',
            old_name='nickmame',
            new_name='nickname',
        ),
    ]
