# Generated by Django 3.2.18 on 2023-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20230429_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historynews',
            name='img_url',
        ),
        migrations.AddField(
            model_name='historynews',
            name='text',
            field=models.TextField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
